# Generated by Django 6.0.3 on 2026-07-08 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskcomment'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'task activity',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='teams.team'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='taskstatus_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('user', 'slug'), name='taskstatus_unique_user_slug'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('team', 'slug'), name='taskstatus_unique_team_slug'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activity_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tasks.task'),
        ),
    ]
