# Generated by Django 6.0.3 on 2026-07-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_teams_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
