# Generated by Django 6.0.3 on 2026-03-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('trello', 'Trello'), ('linear', 'Linear')], max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, default='', max_length=2000)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'provider', 'external_id')},
            },
        ),
    ]
