# Generated by Django 6.0.3 on 2026-07-20 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('trello', 'Trello'), ('linear', 'Linear'), ('skylight', 'Skylight')], max_length=50),
        ),
        migrations.CreateModel(
            name='SkylightConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_encrypted', models.TextField()),
                ('token_encrypted', models.TextField(blank=True, default='')),
                ('token_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_account_id', models.CharField(blank=True, default='', max_length=50)),
                ('calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skylight_connections_made', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skylight_connection', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='SkylightMemberMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('category_label', models.CharField(blank=True, default='', max_length=255)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_mappings', to='integrations.skylightconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skylight_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('connection', 'category_id')},
            },
        ),
    ]
