# Generated by Django 6.0.3 on 2026-07-20 22:08

from django.db import migrations, models


def deactivate_existing_connections(apps, schema_editor):
    # Skylight's password-login endpoint is permanently retired, so every
    # existing connection's stored credential is already useless -- this
    # migration removes the only credential they have. Force teams to
    # explicitly reconnect via the new refresh-token flow rather than sitting
    # silently broken.
    SkylightConnection = apps.get_model("integrations", "SkylightConnection")
    SkylightConnection.objects.update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_externallink_provider_skylightconnection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skylightconnection',
            name='email',
        ),
        migrations.RemoveField(
            model_name='skylightconnection',
            name='password_encrypted',
        ),
        migrations.AddField(
            model_name='skylightconnection',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            deactivate_existing_connections, migrations.RunPython.noop
        ),
    ]
