# Generated by Django 6.0.3 on 2026-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_skylight_refresh_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skylightmembermapping',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='externallink',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('trello', 'Trello'), ('linear', 'Linear')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SkylightConnection',
        ),
        migrations.DeleteModel(
            name='SkylightMemberMapping',
        ),
    ]
