# Generated by Django 6.0.3 on 2026-07-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_default_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_summary_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_summary_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='micropub_endpoint',
        ),
        migrations.RemoveField(
            model_name='user',
            name='micropub_token',
        ),
    ]
